# -*- coding: utf-8 -*-
wordlist = [("1_tateyoko", r"C:\Users\dieul\research18\py2\training\1_tateyoko.wav", u"たてよこ"),
            ("2_tanaita", r"C:\Users\dieul\research18\py2\training\2_tanaita.wav", u"たないた"),
            # ("3_nonezumi", r"C:\Users\dieul\research18\py2\training\3_nonezumi.wav", u"のねずみ"),
            ("4_nagagutsu", r"C:\Users\dieul\research18\py2\training\4_nagagutsu.wav", u"ながぐつ"),
            # ("5_kudamono", r"C:\Users\dieul\research18\py2\training\5_kudamono.wav", u"くだもの"),
            ("6_narezushi", r"C:\Users\dieul\research18\py2\training\6_narezushi.wav", u"なれずし"),
            ("7_megusuri", r"C:\Users\dieul\research18\py2\training\7_megusuri.wav", u"めぐすり"),
            ("8_todomatsu", r"C:\Users\dieul\research18\py2\training\8_todomatsu.wav", u"とどまつ"),
            # ("9_gakusei", r"C:\Users\dieul\research18\py2\training\9_gakusei.wav", u"がくせい"),
            ("10_asemizu", r"C:\Users\dieul\research18\py2\training\10_asemizu.wav", u"あせみず"),
            ("11_hirugoro", r"C:\Users\dieul\research18\py2\training\11_hirugoro.wav", u"ひるごろ"),
            ("12_mizugoke", r"C:\Users\dieul\research18\py2\training\12_mizugoke.wav", u"みずごけ"),
            ("13_aomushi", r"C:\Users\dieul\research18\py2\training\13_aomushi.wav", u"あおむし"),
            # ("14_shibakari", r"C:\Users\dieul\research18\py2\training\14_shibakari.wav", u"しばかり"),
            ("15_bundoki", r"C:\Users\dieul\research18\py2\training\15_bundoki.wav", u"ぶんどき"),
            ("16_kuzunoha", r"C:\Users\dieul\research18\py2\training\16_kuzunoha.wav", u"くずのは"),
            ("17_yakisoba", r"C:\Users\dieul\research18\py2\training\17_yakisoba.wav", u"やきそば"),
            ("18_tateuta", r"C:\Users\dieul\research18\py2\training\18_tateuta.wav", u"たてうた"),
            ("19_raigetsu", r"C:\Users\dieul\research18\py2\training\19_raigetsu.wav", u"らいげつ"),
            ("20_kamakiri", r"C:\Users\dieul\research18\py2\training\20_kamakiri.wav", u"かまきり"),
            ("21_nanohana", r"C:\Users\dieul\research18\py2\training\21_nanohana.wav", u"なのはな"),
            ("22_katakoshi", r"C:\Users\dieul\research18\py2\training\22_katakoshi.wav", u"かたこし"),
            ("23_kakejiku", r"C:\Users\dieul\research18\py2\training\23_kakejiku.wav", u"かけじく"),
            ("24_kafukubu", r"C:\Users\dieul\research18\py2\training\24_kafukubu.wav", u"かふくぶ"),
            ("25_himawari", r"C:\Users\dieul\research18\py2\training\25_himawari.wav", u"ひまわり"),
            # ("26_nokogiri", r"C:\Users\dieul\research18\py2\training\26_nokogiri.wav", u"のこぎり"),
            ("27_azemichi", r"C:\Users\dieul\research18\py2\training\27_azemichi.wav", u"あぜみち"),
            ("28_kanazuchi", r"C:\Users\dieul\research18\py2\training\28_kanazuchi.wav", u"かなづち"),
            ("29_ashiato", r"C:\Users\dieul\research18\py2\training\29_ashiato.wav", u"あしあと"),
            ("30_ayatori", r"C:\Users\dieul\research18\py2\training\30_ayatori.wav", u"あやとり"),
            ("31_hitogomi", r"C:\Users\dieul\research18\py2\training\31_hitogomi.wav", u"ひとごみ"),
            ("32_mainichi", r"C:\Users\dieul\research18\py2\training\32_mainichi.wav", u"まいにち"),
            ("33_tachikuzu", r"C:\Users\dieul\research18\py2\training\33_tachikuzu.wav", u"たちくず"),
            ("34_soragoto", r"C:\Users\dieul\research18\py2\training\34_soragoto.wav", u"そらごと"),
            ("35_sotogake", r"C:\Users\dieul\research18\py2\training\35_sotogake.wav", u"そとがけ"),
            ("36_maigetsu", r"C:\Users\dieul\research18\py2\training\36_maigetsu.wav", u"まいげつ"),
            ("37_shitasaki", r"C:\Users\dieul\research18\py2\training\37_shitasaki.wav", u"したさき"),
            ("38_tamanegi", r"C:\Users\dieul\research18\py2\training\38_tamanegi.wav", u"たまねぎ"),
            ("39_ongaku", r"C:\Users\dieul\research18\py2\training\39_ongaku.wav", u"おんがく"),
            ("40_niwatori", r"C:\Users\dieul\research18\py2\training\40_niwatori.wav", u"にわとり"),
            ]

phraselist= [  ("1_sukidesu", r"C:\Users\dieul\research18\py2\phrases\1_sukidesu.wav", u"すきです"),
                ("2_nihongo", r"C:\Users\dieul\research18\py2\phrases\2_nihongo.wav", u"日本語"),
                ("3_arigatou", r"C:\Users\dieul\research18\py2\phrases\3_arigatou.wav", u"ありがとう"),
                # ("4_ichiji", r"C:\Users\dieul\research18\py2\phrases\4_ichiji.wav", u"一時"),
                ("5_oishidesu", r"C:\Users\dieul\research18\py2\phrases\5_oishidesu.wav", u"おいしいです"),
                ("6_wakarimashita", r"C:\Users\dieul\research18\py2\phrases\6_wakarimashita.wav", u"分かりました"),
# ("7_gomennasai", r"C:\Users\dieul\research18\py2\phrases\7_gomennasai.wav", u"すきです"),
                ("7_gomennasai", r"C:\Users\dieul\research18\py2\phrases\7_gomennasai.wav", u"ごめんなさい"),
                ("8_asagohan", r"C:\Users\dieul\research18\py2\phrases\8_asagohan.wav", u"あさごはん"),
                ("9_onegaishimasu", r"C:\Users\dieul\research18\py2\phrases\9_onegaishimasu.wav", u"おねがいします"),
                ("10_sushiokudasai", r"C:\Users\dieul\research18\py2\phrases\10_sushiokudasai.wav", u"すしおください"),
                ("11_ohayougozaimasu", r"C:\Users\dieul\research18\py2\phrases\11_ohayougozaimasu.wav", u"おはいよございます"),
                ("12_daijoubudesuka", r"C:\Users\dieul\research18\py2\phrases\12_daijoubudesuka.wav", u"だいじょうぶですか"),
                # ("13_doyoobi", r"C:\Users\dieul\research18\py2\phrases\13_doyoobi.wav", u"土曜日")
             ]

wordlist2 = [("1_tateyoko", r"C:\Users\dieul\research18\py2\new_training\1_tateyoko.wav", u"たてよこ"),
            ("2_tanaita", r"C:\Users\dieul\research18\py2\new_training\2_tanaita.wav", u"たないた"),
            ("3_nonezumi", r"C:\Users\dieul\research18\py2\new_training\3_nonezumi.wav", u"のねずみ"),
            ("4_nagagutsu", r"C:\Users\dieul\research18\py2\new_training\4_nagagutsu.wav", u"ながぐつ"),
            ("5_kudamono", r"C:\Users\dieul\research18\py2\new_training\5_kudamono.wav", u"くだもの"),
            ("6_narezushi", r"C:\Users\dieul\research18\py2\new_training\6_narezushi.wav", u"なれずし"),
            ("7_megusuri", r"C:\Users\dieul\research18\py2\new_training\7_megusuri.wav", u"めぐすり"),
            ("8_todomatsu", r"C:\Users\dieul\research18\py2\new_training\8_todomatsu.wav", u"とどまつ"),
            ("9_gakusei", r"C:\Users\dieul\research18\py2\new_training\9_gakusei.wav", u"がくせい"),
            ("10_asemizu", r"C:\Users\dieul\research18\py2\new_training\10_asemizu.wav", u"あせみず"),
            ("11_hirugoro", r"C:\Users\dieul\research18\py2\new_training\11_hirugoro.wav", u"ひるごろ"),
            ("12_mizugoke", r"C:\Users\dieul\research18\py2\new_training\12_mizugoke.wav", u"みずごけ"),
            ("13_aomushi", r"C:\Users\dieul\research18\py2\new_training\13_aomushi.wav", u"あおむし"),
            ("14_shibakari", r"C:\Users\dieul\research18\py2\new_training\14_shibakari.wav", u"しばかり"),
            ("15_bundoki", r"C:\Users\dieul\research18\py2\new_training\15_bundoki.wav", u"ぶんどき"),
            ("16_kuzunoha", r"C:\Users\dieul\research18\py2\new_training\16_kuzunoha.wav", u"くずのは"),
            ("17_yakisoba", r"C:\Users\dieul\research18\py2\new_training\17_yakisoba.wav", u"やきそば"),
            ("18_tateuta", r"C:\Users\dieul\research18\py2\new_training\18_tateuta.wav", u"たてうた"),
            ("19_raigetsu", r"C:\Users\dieul\research18\py2\new_training\19_raigetsu.wav", u"らいげつ"),
            ("20_kamakiri", r"C:\Users\dieul\research18\py2\new_training\20_kamakiri.wav", u"かまきり"),
            ("21_nanohana", r"C:\Users\dieul\research18\py2\new_training\21_nanohana.wav", u"なのはな"),
            ("22_katakoshi", r"C:\Users\dieul\research18\py2\new_training\22_katakoshi.wav", u"かたこし"),
            ("23_kakejiku", r"C:\Users\dieul\research18\py2\new_training\23_kakejiku.wav", u"かけじく"),
            ("24_kafukubu", r"C:\Users\dieul\research18\py2\new_training\24_kafukubu.wav", u"かふくぶ"),
            ("25_himawari", r"C:\Users\dieul\research18\py2\new_training\25_himawari.wav", u"ひまわり"),
            ("26_nokogiri", r"C:\Users\dieul\research18\py2\new_training\26_nokogiri.wav", u"のこぎり"),
            ("27_azemichi", r"C:\Users\dieul\research18\py2\new_training\27_azemichi.wav", u"あぜみち"),
            ("28_kanazuchi", r"C:\Users\dieul\research18\py2\new_training\28_kanazuchi.wav", u"かなづち"),
            ("29_ashiato", r"C:\Users\dieul\research18\py2\new_training\29_ashiato.wav", u"あしあと"),
            ("30_ayatori", r"C:\Users\dieul\research18\py2\new_training\30_ayatori.wav", u"あやとり"),
            ("31_hitogomi", r"C:\Users\dieul\research18\py2\new_training\31_hitogomi.wav", u"ひとごみ"),
            ("32_mainichi", r"C:\Users\dieul\research18\py2\new_training\32_mainichi.wav", u"まいにち"),
            ("33_tachikuzu", r"C:\Users\dieul\research18\py2\new_training\33_tachikuzu.wav", u"たちくず"),
            ("34_soragoto", r"C:\Users\dieul\research18\py2\new_training\34_soragoto.wav", u"そらごと"),
            ("35_sotogake", r"C:\Users\dieul\research18\py2\new_training\35_sotogake.wav", u"そとがけ"),
            ("36_maigetsu", r"C:\Users\dieul\research18\py2\new_training\36_maigetsu.wav", u"まいげつ"),
            ("37_shitasaki", r"C:\Users\dieul\research18\py2\new_training\37_shitasaki.wav", u"したさき"),
            ("38_tamanegi", r"C:\Users\dieul\research18\py2\new_training\38_tamanegi.wav", u"たまねぎ"),
            ("39_ongaku", r"C:\Users\dieul\research18\py2\new_training\39_ongaku.wav", u"おんがく"),
            ("40_niwatori", r"C:\Users\dieul\research18\py2\new_training\40_niwatori.wav", u"にわとり"),
            ]